version: "3.4"

services:
  webserver:
    build:
      dockerfile: ./.docker/bin/php74/Dockerfile
      context: ./
      network: host
    container_name: "${DOCKER_NAME_PREFIX}_webserver"
    links:
      - database
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT-80}:80"
  database:
    build:
      context: "./.docker/bin/mariadb"
    container_name: "${DOCKER_NAME_PREFIX}_database"
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
